### ISSUE TITLE
PF won't scroll on chrome

### ISSUE THREAD

**Issue by mokiwolf** [cluracan/pocketfurc#21]
For some reason when i logged in today, the client stopped scrolling automatically. So, every time anyone says anything I actually have to scroll it myself to go down and see it.

Heres a gif I made of the problem http://gyazo.com/97bcaa6e7928a12d4383c8fa097fc838

**Comment by merklejerk** [comment]
Does resizing the window help? What version of chrome?

**Comment by mokiwolf** [comment]
Resizing doesn't help.
Version 43.0.2357.65 m
Google Chrome is up to date.

Also, it's strange because it doesn't always fail to scroll. There will be a few bubbles that come up just fine, and then it stops again.

**Comment by merklejerk** [comment]
Is there any discernible pattern to the ones that do/don't cause the chat to scroll?

**Comment by mokiwolf** [comment]
Not that I've been able to tell, yet. If it does it again today I'll try to see if there is any pattern at all

**Comment by mokiwolf** [comment]
So, been on it about an hour now... and it's still doing it and has no pattern whatsoever. So strange. I just don't get why it happened all of the sudden.

**Comment by merklejerk** [comment]
Should be fixed in 0.37, which is rolling out.

**Comment by mokiwolf** [comment]
Thanks! It's fixed!
