### ISSUE TITLE
Can't Login since update

### ISSUE THREAD

**Issue by mokiwolf** [cluracan/pocketfurc#24]
Since the 32bit update I haven't been able to login on Pocket :( Any fixes for this yet?

**Comment by merklejerk** [comment]
This is related to the new account system being enforced. I suspect affected alts have been created or merged under the account system and no longer have individual passwords associated with them, breaking INI retrieval and legacy login. You can try assigning a password to the alt through the [web service](http://www.furcadia.com/services/pw/oblivion.php4).

That's just a band-aid though. Pocketfurc will need to move away from legacy logins.

**Comment by englebertbigbic** [comment]
Unfortunately trying to change the password didnt solve the issue, Any possible ETA on when it will be fixed?

**Comment by merklejerk** [comment]
I'll try to suss out the new login protocol this week.

**Comment by merklejerk** [comment]
If anyone has it already documented, I'm all ears.

**Comment by englebertbigbic** [comment]
I have about as much coding knowhow as a stone haha.

**Comment by merklejerk** [comment]
Good news. Chrome version is updated and has been republished to the web store. Android to follow.

**Comment by englebertbigbic** [comment]
Holy moly thats some fast work. Nicely done, at that rate youll give normal devs a bad name haha.
